<?php

namespace App\Services;

use App\Models\Upload;

class DataExporter
{
    public function toCsv(Upload $upload): string
    {
        $records = $upload->cleanedRecords;

        if ($records->isEmpty()) {
            throw new \Exception('No cleaned data to export. Run the cleaner first.');
        }

        $first = $records->first();
        $headers = array_keys($first->cleaned_data);

        $output = fopen('php://temp', 'r+');
        fwrite($output, "\xEF\xBB\xBF"); // BOM for Excel
        fputcsv($output, $headers);

        foreach ($records as $record) {
            $row = [];
            foreach ($headers as $header) {
                $row[] = $record->cleaned_data[$header] ?? '';
            }
            fputcsv($output, $row);
        }

        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);

        return $csv;
    }

    public function toJson(Upload $upload): string
    {
        $records = $upload->cleanedRecords;

        if ($records->isEmpty()) {
            throw new \Exception('No cleaned data to export. Run the cleaner first.');
        }

        $data = $records->map(fn($r) => $r->cleaned_data)->values()->toArray();

        return json_encode([
            'metadata' => [
                'source_file' => $upload->original_filename,
                'total_records' => $records->count(),
                'exported_at' => now()->toIso8601String(),
                'readiness_score' => $upload->readinessReport?->score,
            ],
            'records' => $data,
        ], JSON_PRETTY_PRINT);
    }

    /**
     * MedPro-ready CSV — only matched fields, in standard order, aligned correctly.
     */
    public function toMedProCsv(Upload $upload): string
    {
        $records = $upload->cleanedRecords;

        if ($records->isEmpty()) {
            throw new \Exception('No cleaned data to export. Run the cleaner first.');
        }

        $matchedFields = $upload->matches()->pluck('med_field')->unique()->toArray();

        $standardOrder = [
            'full_name', 'date_of_birth', 'mobile_number', 'sex',
            'city', 'national_id', 'blood_type', 'emergency_contact',
        ];

        // Only include fields the user actually matched — preserves column alignment
        $headers = array_values(array_intersect($standardOrder, $matchedFields));

        $output = fopen('php://temp', 'r+');
        fwrite($output, "\xEF\xBB\xBF");
        fputcsv($output, $headers);

        foreach ($records as $record) {
            $row = [];
            foreach ($headers as $field) {
                $row[] = $record->cleaned_data[$field] ?? '';
            }
            fputcsv($output, $row);
        }

        rewind($output);
        $csv = stream_get_contents($output);
        fclose($output);

        return $csv;
    }

    public function toReport(Upload $upload, array $gapAnalysis): string
    {
        $lines = [];
        $lines[] = str_repeat('=', 60);
        $lines[] = '  MEDBRIDGE READINESS REPORT';
        $lines[] = str_repeat('=', 60);
        $lines[] = '';
        $lines[] = 'File: ' . $upload->original_filename;
        $lines[] = 'Generated: ' . now()->format('F j, Y \a\t H:i');
        $lines[] = '';
        $lines[] = '─── SUMMARY ───';
        $lines[] = 'Total Rows:     ' . number_format($upload->row_count);
        $lines[] = 'Fields Mapped:  ' . $gapAnalysis['matched_count'] . ' of ' . $gapAnalysis['total_fields'] . ' (' . $gapAnalysis['coverage_pct'] . '%)';
        if ($upload->readinessReport) {
            $lines[] = 'Readiness Score: ' . $upload->readinessReport->score . '%';
            $lines[] = 'Status:          ' . $upload->readinessReport->summary;
        }
        $lines[] = '';
        $lines[] = '─── MODULE STATUS ───';
        $lines[] = 'Ready:    ' . $gapAnalysis['ready_modules'] . ' of ' . $gapAnalysis['total_modules'];
        $lines[] = 'Partial:  ' . $gapAnalysis['partial_modules'];
        $lines[] = 'Locked:   ' . $gapAnalysis['locked_modules'];
        $lines[] = '';
        $lines[] = '─── RECOMMENDED ACTIONS ───';
        foreach ($gapAnalysis['recommendations'] as $rec) {
            $lines[] = '• Add "' . $rec['label'] . '" — unlocks ' . $rec['impact'] . ' module(s)';
        }
        $lines[] = '';
        $lines[] = '─── MISSING FIELDS ───';
        if (empty($gapAnalysis['missing_fields'])) {
            $lines[] = 'None! All standard fields are mapped.';
        } else {
            foreach ($gapAnalysis['missing_fields'] as $field) {
                $lines[] = '• ' . str_replace('_', ' ', ucwords($field, '_'));
            }
        }
        $lines[] = '';
        $lines[] = str_repeat('=', 60);
        $lines[] = 'Generated by medbridGe — Scan. Score. Sell.';

        return implode("\n", $lines);
    }
}